[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "easysql"
authors = [{name = "easy_sql", email = "easy_sql@thoughtworks.com"}]
dynamic = ["version", "description"]
